// Generated by ReScript, PLEASE EDIT WITH CARE


function render(state) {
  if (typeof state === "number") {
    console.log("choose a doctor step");
    return ;
  }
  if (state.TAG === /* PickTimeSlot */0) {
    console.log("pick a time slot");
    return ;
  }
  console.log("fill in patient information");
}

export {
  render ,
}
/* No side effect */
