// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function formatDoctor(doctor) {
  return "Dr. " + doctor.lastName;
}

var drHouseName = "Dr. House";

function Doctor(props) {
  return JsxRuntime.jsx("h1", {
              children: Caml_option.some("Dr. " + props.doctor.lastName)
            });
}

function format(user) {
  return "Dr." + user.lastName;
}

function Doctor$User(props) {
  return JsxRuntime.jsx("h1", {
              children: Caml_option.some("Dr." + props.doctor.lastName)
            });
}

var User = {
  format: format,
  make: Doctor$User
};

var doctorHouse = {
  id: 1,
  firstName: "Gregory",
  lastName: "House"
};

var make = Doctor;

export {
  doctorHouse ,
  formatDoctor ,
  drHouseName ,
  make ,
  User ,
}
/* react/jsx-runtime Not a pure module */
