// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Demo from "./Demo.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

var React18 = {};

var root = document.querySelector("#app");

if (!(root == null)) {
  var reactRoot = Client.createRoot(root);
  reactRoot.render(JsxRuntime.jsx(Demo.make, {}));
}

export {
  React18 ,
}
/* root Not a pure module */
